### ISSUE TITLE
An error during audio connection Call.getCallState() on a null object reference

### ISSUE THREAD

**Issue by semeruk** [Nexmo/conversation-android-quickstart#19]
I made a Stitch Android app via this documentation https://developer.nexmo.com/stitch/in-app-voice/guides/2-calling-users and encountered some difficulties with solving an error during audio connection:

java.lang.NullPointerException: Attempt to invoke virtual method 'com.nexmo.sdk.conversation.client.Call$CALL_STATE com.nexmo.sdk.conversation.client.Call.getCallState()' on a null object reference
07-05 16:35:57.927 29105-29303/com.beskydsoft.androidwebrtcclient W/System.err:     at com.nexmo.sdk.conversation.client.SocketEventHandler.onMessageReceived(SocketEventHandler.java:510)
        at com.nexmo.sdk.conversation.client.SocketClient$51.onData(SocketClient.java:1020)
        at com.nexmo.sdk.conversation.client.SocketClient$Listener.call(SocketClient.java:1103)
        at com.nexmo.sdk.conversation.core.client.Router.dispatch(Router.java:213)
        at com.nexmo.sdk.conversation.core.client.Router.access$200(Router.java:48)
        at com.nexmo.sdk.conversation.core.client.Router$2.call(Router.java:262)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Manager.ondecoded(Manager.java:427)
        at io.socket.client.Manager.access$1600(Manager.java:30)
        at io.socket.client.Manager$7.call(Manager.java:403)
07-05 16:35:57.928 29105-29303/com.beskydsoft.androidwebrtcclient W/System.err:     at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
        at io.socket.client.Manager.ondata(Manager.java:419)
        at io.socket.client.Manager.access$1000(Manager.java:30)
        at io.socket.client.Manager$2.call(Manager.java:370)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
07-05 16:35:57.929 29105-29303/com.beskydsoft.androidwebrtcclient W/System.err:     at io.socket.engineio.client.Socket$5.call(Socket.java:335)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
        at io.socket.engineio.client.Transport.onData(Transport.java:118)
        at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
07-05 16:35:57.930 29105-29303/com.beskydsoft.androidwebrtcclient W/System.err:     at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

Any ideas of what I'm missing?

**Comment by ChrisGuzman** [comment]
What part of the guide is throwing that error?
